name: "add num"
description: "text"
author: "mark"
inputs:
  num:
    description: "num you want"
    required: true
  is_empty:
    description: "is empty"
    required: true
outputs:
  my_const:
    description: "always 666"
runs:
  using: "docker"
  image: "Dockerfile"

