name: My Workflow
on:
  workflow_dispatch:
    inputs:
      someinput:
        type: choice
        options:
          - notempty
          - empty

jobs:
  first_job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: add number
        id: addn
        uses: ./.github/actions/addnum
        with:
          num: 71
          is_empty: ${{ inputs.someinput }}
      - run: |
          echo "Const is: ${{ steps.addn.outputs.my_const }}"
      - uses: peter-evans/create-pull-request@v5
        if: ${{ steps.addn.outputs.my_const }}
        with:
          title: "New PR haha: ${{ steps.addn.outputs.my_const }}"
